version: "3.8"

services:
  account-service:
    image: byusluer/account-service
    ports:
      - "8080:8080"
    networks:
     - byusluer-network
  loan-service:
    image: byusluer/loan-service
    ports:
      - "8090:8090"
    networks:
      - byusluer-network
  card-service:
    image: byusluer/card-service
    ports:
      - "9000:9000"
    networks:
      - byusluer-network
networks:
  byusluer-network: