version: "3.8"
services:
  config-server:
    image: byusluer/account-service
    ports:
      - "8071:8071"
    networks:
      - byusluer-network
  account-service:
    image: byusluer/account-service
    ports:
      - "8080:8080"
    networks:
     - byusluer-network
    depends_on:
      - config-server
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8071
  loan-service:
    image: byusluer/loan-service
    ports:
      - "8090:8090"
    networks:
      - byusluer-network
    depends_on:
      - config-server
    deploy:
        restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
          window: 120s
    environment:
        SPRING_PROFILES_ACTIVE: prod
        SPRING_CONFIG_IMPORT: configserver:http://config-server:8071
  card-service:
    image: byusluer/card-service
    ports:
      - "9000:9000"
    networks:
      - byusluer-network
    depends_on:
      - config-server
    deploy:
        restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
          window: 120s
    environment:
       SPRING_PROFILES_ACTIVE: prod
       SPRING_CONFIG_IMPORT: configserver:http://config-server:8071
networks:
  byusluer-network: