server:
  port: 8080

spring:
  application:
    name: accounts

  datasource:
    url:  jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
  config:
    import: optional:configserver:http://localhost:8071
  profiles:
    active: dev
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
  info:
      env:
        enabled: true
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8070/eureka/

info:
  app:
    name: Account MicroService
    description:   Account Ws Application
    version: 1.0.0
endpoints:
  shutdown:
    enabled: true
