server:
  port: 8080

spring:
  application:
    name: accounts

  datasource:
    url:  jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
  config:
    import: optional:configserver:http://localhost:8071
  profiles:
    active: dev
management:
  endpoints:
    web:
      exposure:
        include: '*'
