accounts:
  msg: Welcome to the Byusluer Banking App
  build:
    version:3
  mailDetails:
    hostName: byusluer-bankin-devg@internatiol.com
    port: 9001
    from: dev-accounts@byusluer-banking.com
    subject: Your Account Details Byusluer Banking -dev
  activeBranches:
    - Istanbul_dev
    - Ankara_dev
    - Antalya_dev

