accounts:
  msg: Welcome to the Byusluer Banking App
  build:
    version:3
  mailDetails:
    hostName: byusluer-banking@internatiol.com
    port: 9000
    from: default-accounts@byusluer-banking.com
    subject: Your Account Details Byusluer Banking -default
  activeBranches:
    - Istanbul
    - Ankara
    - Antalya