server:
  port: 9000

spring:
  application:
    name: cards

  datasource:
    url:  jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
  config:
    import: optional:configserver:http://localhost:8071
  profiles:
    active: dev